// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVRWAE7ftZG5N83bNssXQqshuhyWH5mR4',
    appId: '1:976805418776:web:0983fd71ed077c075bb06d',
    messagingSenderId: '976805418776',
    projectId: 'ecommerce190722',
    authDomain: 'ecommerce190722.firebaseapp.com',
    storageBucket: 'ecommerce190722.appspot.com',
    measurementId: 'G-TF3VXYNFVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfX1TNd9hefOhqHUVsFZyVGI5JvWRwBp0',
    appId: '1:976805418776:android:47eeb2cda56cd9ef5bb06d',
    messagingSenderId: '976805418776',
    projectId: 'ecommerce190722',
    storageBucket: 'ecommerce190722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWq0yNEvxCimBap68CthJtMbbRW0JlU0',
    appId: '1:976805418776:ios:c13904efa9d6b2df5bb06d',
    messagingSenderId: '976805418776',
    projectId: 'ecommerce190722',
    storageBucket: 'ecommerce190722.appspot.com',
    androidClientId: '976805418776-4sburst9c2rdh8qiuuce0nu2ig4s239h.apps.googleusercontent.com',
    iosClientId: '976805418776-qul26bfuiqrtpbr5r91tc84ftb773vmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerfirebaseecom',
  );
}
